{
  "nhl": [
    {"sport_tag": "🏒 ACTIVE HOCKEY SLATE", "game": "Ottawa Senators @ Detroit Red Wings", "live_clock": "7:00 PM ET", "score_string": "0 - 0", "closing_line": "O/U 6.5", "sim_total": "Sim Total: 5.5", "pacing_status": "Pacing 📉 UNDER", "players": [{"name": "Dylan Larkin", "position": "C", "target": "Over 3.5 Shots on Goal Floor", "is_floor": true}, {"name": "Tim Stützle", "position": "C", "target": "Under 2.5 SOG Ceiling", "is_floor": false}], "morale": [{"unit": "Sens Front 6 Pacing", "status": "WARN", "alert_text": "Early season physical fatigue penalty flagged on transition defense."}]},
    {"sport_tag": "🏒 ACTIVE HOCKEY SLATE", "game": "New York Islanders @ New York Rangers", "live_clock": "7:30 PM ET", "score_string": "0 - 0", "closing_line": "O/U 5.5", "sim_total": "Sim Total: 6.0", "pacing_status": "Pacing 🔥 EVALUATING", "players": [{"name": "Artemi Panarin", "position": "LW", "target": "Over 2.5 Shots on Goal Floor", "is_floor": true}, {"name": "Bo Horvat", "position": "C", "target": "Under 3.5 SOG Ceiling", "is_floor": false}], "morale": [{"unit": "Islanders Blue Line", "status": "WARN", "alert_text": "High expected defensive zone pressure. Ranger SOG floor insulated."}]},
    {"sport_tag": "🏒 ACTIVE HOCKEY SLATE", "game": "Florida Panthers @ Los Angeles Kings", "live_clock": "10:00 PM ET", "score_string": "0 - 0", "closing_line": "O/U 6.0", "sim_total": "Sim Total: 7.0", "pacing_status": "Pacing 💥 OVER", "players": [{"name": "Matthew Tkachuk", "position": "RW", "target": "Over 3.5 Shots on Goal Floor", "is_floor": true}, {"name": "Anze Kopitar", "position": "C", "target": "Under 2.5 SOG Ceiling", "is_floor": false}], "morale": [{"unit": "Kings Netminder Group", "status": "WARN", "alert_text": "Public Favorite Trap: High volume public backing exposure risk active."}]},
    {"sport_tag": "🏒 ACTIVE HOCKEY SLATE", "game": "Carolina Hurricanes @ Montreal Canadiens", "live_clock": "7:00 PM ET", "score_string": "0 - 0", "closing_line": "O/U 6.0", "sim_total": "Sim Total: 5.5", "pacing_status": "Pacing 📉 UNDER", "players": [{"name": "Sebastian Aho", "position": "C", "target": "Over 2.5 SOG Floor", "is_floor": true}, {"name": "Nick Suzuki", "position": "C", "target": "Under 2.5 SOG Ceiling", "is_floor": false}], "morale": [{"unit": "Canadiens Goalies", "status": "WARN", "alert_text": "78% public consensus backing over-inflated total profile."}]},
    {"sport_tag": "🏒 ACTIVE HOCKEY SLATE", "game": "Nashville Predators @ Toronto Maple Leafs", "live_clock": "7:00 PM ET", "score_string": "0 - 0", "closing_line": "O/U 6.5", "sim_total": "Sim Total: 7.0", "pacing_status": "Pacing 💥 OVER", "players": [{"name": "Auston Matthews", "position": "C", "target": "Over 4.5 SOG Floor", "is_floor": true}, {"name": "Filip Forsberg", "position": "LW", "target": "Under 3.5 SOG Ceiling", "is_floor": false}], "morale": [{"unit": "Predators Neutral Zone", "status": "WARN", "alert_text": "Game-Script Panic Threshold: High penalty minute risk trajectory."}]},
    {"sport_tag": "🏒 ACTIVE HOCKEY SLATE", "game": "Minnesota Wild @ Buffalo Sabres", "live_clock": "7:00 PM ET", "score_string": "0 - 0", "closing_line": "O/U 5.5", "sim_total": "Sim Total: 5.0", "pacing_status": "Pacing 📉 UNDER", "players": [{"name": "Kirill Kaprizov", "position": "LW", "target": "Over 3.5 SOG Floor", "is_floor": true}, {"name": "Tage Thompson", "position": "C", "target": "Under 3.5 SOG Ceiling", "is_floor": false}], "morale": [{"unit": "Sabres Offensive Flow", "status": "WARN", "alert_text": "High volume public backing on the over creates contrarian value under."}]},
    {"sport_tag": "🏒 ACTIVE HOCKEY SLATE", "game": "St. Louis Blues @ Chicago Blackhawks", "live_clock": "8:00 PM ET", "score_string": "0 - 0", "closing_line": "O/U 5.5", "sim_total": "Sim Total: 6.0", "pacing_status": "Pacing 🔥 STABLE", "players": [{"name": "Connor Bedard", "position": "C", "target": "Over 3.5 SOG Floor", "is_floor": true}, {"name": "Robert Thomas", "position": "C", "target": "Under 2.5 SOG Ceiling", "is_floor": false}], "morale": [{"unit": "Blues Penalty Kill", "status": "WARN", "alert_text": "High expected box time trajectory. Connor Bedard powerplay insulation high."}]},
    {"sport_tag": "🏒 ACTIVE HOCKEY SLATE", "game": "Vegas Golden Knights @ Seattle Kraken", "live_clock": "9:40 PM ET", "score_string": "0 - 0", "closing_line": "O/U 5.5", "sim_total": "Sim Total: 5.5", "pacing_status": "Pacing 🔥 STABLE", "players": [{"name": "Jack Eichel", "position": "C", "target": "Over 3.5 SOG Floor", "is_floor": true}, {"name": "Jared McCann", "position": "C", "target": "Under 2.5 SOG Ceiling", "is_floor": false}], "morale": [{"unit": "Kraken Backcheck", "status": "WARN", "alert_text": "Zone tracking identifies low volume under insulation."}]}
  ],
  "nfl": [
    {"sport_tag": "🏈 CONTRARIAN FOOTBALL SLATE", "game": "Detroit Lions @ Arizona Cardinals", "live_clock": "SUN - 4:25 PM", "score_string": "PRE-GAME", "closing_line": "O/U 53.5", "sim_total": "CEE Projected: 57", "pacing_status": "Pacing 💥 OVER", "players": [{"name": "Jared Goff", "position": "QB", "target": "Over 248.5 Passing Yards Floor", "is_floor": true}, {"name": "Amon-Ra St. Brown", "position": "WR", "target": "Under 7.5 Receptions Ceiling", "is_floor": false}], "morale": [{"unit": "Cardinals Secondary", "status": "WARN", "alert_text": "Heavy public money fade opportunity. Volume is exceptionally high."}]},
    {"sport_tag": "🏈 CONTRARIAN FOOTBALL SLATE", "game": "Tampa Bay Buccaneers @ Dallas Cowboys", "live_clock": "THU - 8:15 PM", "score_string": "PRE-GAME", "closing_line": "O/U 47.5", "sim_total": "CEE Projected: 49", "pacing_status": "Pacing 🔥 STABLE", "players": [{"name": "Dak Prescott", "position": "QB", "target": "Over 258.5 Pass Yards Floor", "is_floor": true}, {"name": "CeeDee Lamb", "position": "WR", "target": "Under 7.5 Rec Ceiling", "is_floor": false}], "morale": [{"unit": "Buccaneers Front 7", "status": "WARN", "alert_text": "AWS Pass-Rush Score: Deficit tracked. Dak floor highly insulated."}]},
    {"sport_tag": "🏈 CONTRARIAN FOOTBALL SLATE", "game": "Chicago Bears @ Green Bay Packers", "live_clock": "SUN - 1:00 PM", "score_string": "PRE-GAME", "closing_line": "O/U 44.5", "sim_total": "CEE Projected: 41", "pacing_status": "Pacing 📉 UNDER", "players": [{"name": "D'Andre Swift", "position": "RB", "target": "Over 62.5 Rush Yards Floor", "is_floor": true}, {"name": "DJ Moore", "position": "WR", "target": "Under 5.5 Rec Ceiling", "is_floor": false}], "morale": [{"unit": "Packers Run Def", "status": "WARN", "alert_text": "Morale Deficit Flag engaged. Explosive public favorite trap active."}]},
    {"sport_tag": "🏈 CONTRARIAN FOOTBALL SLATE", "game": "Minnesota Vikings @ New Orleans Saints", "live_clock": "SUN - 1:00 PM", "score_string": "PRE-GAME", "closing_line": "O/U 41.5", "sim_total": "CEE Projected: 46", "pacing_status": "Pacing 🔥 OVER", "players": [{"name": "Alvin Kamara", "position": "RB", "target": "Over 4.5 Live Receptions Floor", "is_floor": true}, {"name": "Chris Olave", "position": "WR", "target": "Under 6.5 Live Rec Ceiling", "is_floor": false}], "morale": [{"unit": "Saints O-Line", "status": "WARN", "alert_text": "Game-Script Panic Threshold: High pocket pressure collapse expected."}]},
    {"sport_tag": "🏈 CONTRARIAN FOOTBALL SLATE", "game": "Philadelphia Eagles @ Jacksonville Jaguars", "live_clock": "SUN - 9:30 AM", "score_string": "PRE-GAME", "closing_line": "O/U 46.5", "sim_total": "CEE Projected: 42", "pacing_status": "Pacing 📉 UNDER", "players": [{"name": "Saquon Barkley", "position": "RB", "target": "Over 78.5 Rushing Yards Floor", "is_floor": true}, {"name": "DeVonta Smith", "position": "WR", "target": "Under 5.5 Rec Ceiling", "is_floor": false}], "morale": [{"unit": "Eagles Pass Block", "status": "WARN", "alert_text": "London Venue Filter: High travel fatigue tracking forces heavy run script."}]},
    {"sport_tag": "🏈 CONTRARIAN FOOTBALL SLATE", "game": "New York Giants @ Washington Commanders", "live_clock": "SUN - 1:00 PM", "score_string": "PRE-GAME", "closing_line": "O/U 43.5", "sim_total": "CEE Projected: 48", "pacing_status": "Pacing 🔥 OVER", "players": [{"name": "Jayden Daniels", "position": "QB", "target": "Over 224.5 Pass Yards Floor", "is_floor": True}, {"name": "Malik Nabers", "position": "WR", "target": "Under 6.5 Rec Ceiling", "is_floor": false}], "morale": [{"unit": "Giants Secondary", "status": "WARN", "alert_text": "Morale Deficit Stream: Coverage metrics signaling structural breakdown."}]},
    {"sport_tag": "🏈 CONTRARIAN FOOTBALL SLATE", "game": "Cleveland Browns @ New York Jets", "live_clock": "SUN - 1:00 PM", "score_string": "PRE-GAME", "closing_line": "O/U 39.5", "sim_total": "CEE Projected: 36", "pacing_status": "Pacing 📉 UNDER", "players": [{"name": "Breece Hall", "position": "RB", "target": "Over 68.5 Rushing Yards Floor", "is_floor": True}, {"name": "Amari Cooper", "position": "WR", "target": "Under 4.5 Rec Ceiling", "is_floor": false}], "morale": [{"unit": "Browns O-Line", "status": "WARN", "alert_text": "Heavy pass rush pressure metric surge expected. Total insulated on under."}]},
    {"sport_tag": "🏈 CONTRARIAN FOOTBALL SLATE", "game": "Indianapolis Colts @ Pittsburgh Steelers", "live_clock": "SUN - 1:00 PM", "score_string": "PRE-GAME", "closing_line": "O/U 42.5", "sim_total": "CEE Projected: 40", "pacing_status": "Pacing 📉 UNDER", "players": [{"name": "Jonathan Taylor", "position": "RB", "target": "Over 74.5 Rush Yards Floor", "is_floor": True}, {"name": "George Pickens", "position": "WR", "target": "Under 5.5 Rec Ceiling", "is_floor": false}], "morale": [{"unit": "Colts Run Defense", "status": "WARN", "alert_text": "Highly backed public home favorite asset fade marker active."}]},
